package projeto_base;

import projeto_base.model.Cliente;
import projeto_base.model.Funcionario;
import projeto_base.repository.ClienteRepository;
import projeto_base.repository.FuncionarioRepository;

public class TelaLogin extends javax.swing.JFrame {

    private static final Cliente Cliente_Padrao;

    private static final Funcionario Funcionario_Padrao;

    static {

        Cliente_Padrao = new Cliente(
                0,
                "Teste",
                "000.000.000-00",
                "99999-1111",
                "teste@email.com",
                "Rua Teste"
        );
        Funcionario_Padrao = new Funcionario(
                0,
                "Teste Func",
                "000.000.000-10",
                "Vendedora",
                "2500"
        );
        
        ClienteRepository.salvar(Cliente_Padrao);
        FuncionarioRepository.salvar(Funcionario_Padrao);

    }

    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonLoginCliente = new javax.swing.JButton();
        jButtonLoginFuncionario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonLoginCliente.setText("Cliente");
        jButtonLoginCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginClienteActionPerformed(evt);
            }
        });

        jButtonLoginFuncionario.setText("Funcionário");
        jButtonLoginFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginFuncionarioActionPerformed(evt);
            }
        });

        jLabel1.setText("Você é :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jButtonLoginCliente)
                        .addGap(60, 60, 60)
                        .addComponent(jButtonLoginFuncionario))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel1)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLoginCliente)
                    .addComponent(jButtonLoginFuncionario))
                .addContainerGap(159, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginClienteActionPerformed
        TelaPrincipal tela = new TelaPrincipal(Cliente_Padrao);

        tela.setVisible(true);

        dispose();
    }//GEN-LAST:event_jButtonLoginClienteActionPerformed

    private void jButtonLoginFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginFuncionarioActionPerformed

        TelaPrincipal tela = new TelaPrincipal(Funcionario_Padrao);

        tela.setVisible(true);

        dispose();
    }//GEN-LAST:event_jButtonLoginFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLoginCliente;
    private javax.swing.JButton jButtonLoginFuncionario;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
